---
version: '3'
networks:
    ssonet:
        ipam:
            config:
                - subnet: 172.23.0.0/24
volumes:
    local_postgres_data: {}
    local_postgres_data_backups: {}
    local_zookeeper_data: {}
    local_kafka_data: {}
services:
    kcpostgres:
        container_name: kcpostgres
        image: postgres:12.2
        environment:
            POSTGRES_DB: keycloak
            POSTGRES_USER: keycloak
            POSTGRES_PASSWORD: keycloak
        networks:
            ssonet:
                ipv4_address: 172.23.0.2
    sso.local.redhat.com:
        container_name: sso.local.redhat.com
        image: quay.io/keycloak/keycloak:11.0.0
        environment:
            DB_VENDOR: postgres
            DB_ADDR: kcpostgres
            DB_DATABASE: keycloak
            DB_USER: keycloak
            DB_PASSWORD: keycloak
            PROXY_ADDRESS_FORWARDING: 'true'
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: password
        ports:
            - 8443:8443
        depends_on:
            - kcpostgres
        networks:
            ssonet:
                ipv4_address: 172.23.0.3
    kcadmin:
        container_name: kcadmin
        image: python:3
        build:
            context: srv/keycloak_admin
        volumes:
            - ./srv/keycloak_admin:/app
        depends_on:
            - sso.local.redhat.com
        command: /bin/bash -c "cd /app && pip install -r requirements.txt && python -c 'from kchelper import init_realm; init_realm()' && flask run --host=0.0.0.0 --port=80"
        networks:
            ssonet:
                ipv4_address: 172.23.0.4
    insights_proxy:
        container_name: insights_proxy
        image: redhatinsights/insights-proxy
        ports:
            - 1337:1337
        environment:
            - PLATFORM=linux
            - CUSTOM_CONF=true
        security_opt:
            - label=disable
        extra_hosts:
            - prod.foo.redhat.com:127.0.0.1
        volumes:
            - ./srv/www/spandx.config.js:/config/spandx.config.js
    webroot:
        container_name: webroot
        image: nginx
        volumes:
            - ./srv/www:/usr/share/nginx/html
        command:
            - nginx-debug
            - -g
            - daemon off;
    chrome:
        container_name: chrome
        image: nginx
        volumes:
            - ./srv/insights-chrome:/usr/share/nginx/html
        command:
            - nginx-debug
            - -g
            - daemon off;
    chrome_beta:
        container_name: chrome_beta
        image: nginx
        volumes:
            - ./srv/insights-chrome:/usr/share/nginx/html
        command:
            - nginx-debug
            - -g
            - daemon off;
    entitlements:
        container_name: entitlements
        image: python:3
        build:
            context: srv/entitlements
        volumes:
            - ./srv/entitlements:/app
        command: /bin/bash -c "cd /app && pip install -r requirements.txt && python api.py"
    rbac:
        container_name: rbac
        image: python:3
        build:
            context: srv/rbac
        volumes:
            - ./srv/rbac:/app
        command: /bin/bash -c "cd /app && pip install -r requirements.txt && python api.py"
    aafrontend:
        container_name: aafrontend
        image: node:10.22.0
        user: node
        ports:
            - 8002:8002
        environment:
            DEBUG: express:*
        command: /bin/bash -c "cd /app && npm install && npm run start:container"
        volumes:
            - ./srv/tower-analytics-frontend:/app:rw
    aabackend:
        container_name: aabackend
        image: python:3
        build:
            context: ./srv/aa_backend_mock
        environment:
            API_SECURE: '1'
        volumes:
            - ./srv/aa_backend_mock:/app
        command: /bin/bash -c "cd /app && pip install -r requirements.txt && python api.py"
    integration:
        container_name: integration
        image: aa_integration:latest
        build:
            context: ./srv/integration_tests
            dockerfile: Dockerfile
        volumes:
            - ./srv/integration_tests:/app:rw
        network_mode: host
        user: node
        cap_add:
            - SYS_ADMIN
        extra_hosts:
            - prod.foo.redhat.com:127.0.0.1
            - sso.local.redhat.com:172.23.0.3
        command: /bin/bash -c "cd /app && npm install && ./wait_for_stack.sh && timeout -s SIGKILL 1000s ./node_modules/jest/bin/jest.js src/index.test.js"
