---
version: '3'
networks:
    ssonet:
        ipam:
            config:
                - subnet: 172.23.0.0/24
volumes:
    local_postgres_data: {}
    local_postgres_data_backups: {}
    local_zookeeper_data: {}
    local_kafka_data: {}
services:
    sso.local.redhat.com:
        container_name: sso.local.redhat.com
        image: quay.io/keycloak/keycloak:11.0.0
        environment:
            DB_VENDOR: h2
            PROXY_ADDRESS_FORWARDING: 'true'
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: password
        expose:
            - 8443
    kcadmin:
        container_name: kcadmin
        image: python:3
        build:
            context: srv/keycloak_admin
        volumes:
            - ./srv/keycloak_admin:/app
        depends_on:
            - sso.local.redhat.com
        command: /bin/bash -c "cd /app && pip install -r requirements.txt && python -c 'from kchelper import init_realm; init_realm()' && flask run --host=0.0.0.0 --port=80"
    webroot:
        container_name: webroot
        image: nginx
        volumes:
            - ./srv/www:/usr/share/nginx/html
            - ./srv/nginx.conf.d:/etc/nginx/conf.d
        command:
            - nginx-debug
            - -g
            - daemon off;
    entitlements:
        container_name: entitlements
        image: python:3
        build:
            context: srv/entitlements
        volumes:
            - ./srv/entitlements:/app
        command: /bin/bash -c "cd /app && pip install -r requirements.txt && python api.py"
    rbac:
        container_name: rbac
        image: python:3
        build:
            context: srv/rbac
        volumes:
            - ./srv/rbac:/app
        command: /bin/bash -c "cd /app && pip install -r requirements.txt && python api.py"
    squid:
        container_name: squid
        image: datadog/squid
        ports:
            - 3128:3128
        volumes:
            - ./srv/squid/conf:/etc/squid
            - ./srv/squid/logs:/var/log/squid
    prod.foo.redhat.com:
        container_name: prod.foo.redhat.com
        image: redhatinsights/insights-proxy
        ports:
            - 8443:8443
        environment:
            SPANDX_PORT: 8443
        security_opt:
            - label=disable
        extra_hosts:
            - prod.foo.redhat.com:127.0.0.1
        volumes:
            - ./srv/www/spandx.config.js:/config/spandx.config.js
    aabackend:
        container_name: aabackend
        image: python:3
        build:
            context: ./srv/aa_backend_mock
        environment:
            API_SECURE: '1'
        volumes:
            - ./srv/aa_backend_mock:/app
        command: /bin/bash -c "cd /app && pip install -r requirements.txt && python api.py"
    integration:
        container_name: integration
        ipc: host
        image: aa_integration:latest
        build:
            context: ./srv/integration_tests
            dockerfile: Dockerfile.cypress
        volumes:
            - ./srv/integration_tests:/app:rw
        user: node
        cap_add:
            - SYS_ADMIN
        entrypoint: ''
        depends_on:
            - sso.local.redhat.com
            - kcadmin
            - aabackend
        command: /bin/bash -c "cd /app && npm install && ./wait_for_stack.sh && timeout -s SIGKILL 1000s cypress run --headless --browser chrome --spec cypress/integration/automation-analytics.js"
