#!/usr/bin/env python

import argparse
import subprocess
import sys

def run_command(cmd):
    p = subprocess.Popen(cmd, shell=True)
    return p


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--command', action='append')
    args = parser.parse_args()

    pids = []

    try:
        for command in args.command:
            pids.append(run_command(command))
       
        for pid in pids:
            pid.wait()

    except KeyboardInterrupt:
        print('# KILLING STACKS ...')
        for pid in pids:
            pid.kill()


if __name__ == "__main__":
    main()
