- name: setup docker
  hosts: all
  connection: local
  become: True
  vars:
    docker_users:
      - vagrant
  tasks:
    - include_role:
        name: geerlingguy.docker
    - include_role:
        name: cypress_deps

- name: misc
  hosts: all
  connection: local
  vars:
    hosts_entries:
      - 127.0.0.1 prod.foo.redhat.com
      - 127.0.0.1 stage.foo.redhat.com
      - 127.0.0.1 qa.foo.redhat.com
      - 127.0.0.1 ci.foo.redhat.com
      - 172.23.0.3 sso.local.redhat.com
  tasks:
    - apt: name=python3-virtualenv
      become: True
    - apt: name=python-is-python3
      become: True
    - apt: name=tmux
      become: True
    - apt: name=vim
      become: True
    - shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash creates=/home/vagrant/.nvm/nvm-exec
    - shell: /bin/bash -c ". ~/.nvm/nvm.sh && nvm install 10 creates=/home/vagrant/.nvm/versions/node"
    - copy:
        src: .tmux.conf
        dest: /home/vagrant/.tmux.conf
    - copy:
        src: .vimrc
        dest: /home/vagrant/.vimrc

    - lineinfile:
        path: /etc/hosts
        regexp: "{{ item }}"
        line: "{{ item }}"
      loop: "{{ hosts_entries }}"
      become: True

