# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: make the venv
        run: |
          pip3 install --user virtualenv
          python3 -m virtualenv --python=$(which python3) venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: make the stack
        run: |
          source venv/bin/activate
          make stack_ci_cypress_debug

      - name: save the screenshots 
        uses: actions/upload-artifact@v2
        with:
          name: screens
          path: ./srv/integration_tests/cypress/screenshots
          retention-days: 5
        if: always()

      - name: save the video 
        uses: actions/upload-artifact@v2
        with:
          name: video
          path: ./srv/integration_tests/cypress/videos
          retention-days: 5
        if: always()      
